name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag'
        required: true
        default: 'v2026.1.31.1'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - uses: ncipollo/release-action@v1
      with:
        tag: ${{ inputs.tag }}
        bodyFile: ReleaseBodyFile.md
